"""updated artists

Revision ID: 722ed00c082c
Revises: 452fc23be696
Create Date: 2022-10-20 12:40:18.294411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722ed00c082c'
down_revision = '452fc23be696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
